"""add deep research workflow

Revision ID: 1c54143c9885
Revises: ca42d5c817e9
Create Date: 2026-07-24 17:52:45.151685
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "1c54143c9885"
down_revision: str | Sequence[str] | None = "ca42d5c817e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_tasks",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("allow_web", sa.Boolean(), nullable=False),
        sa.Column("use_memory", sa.Boolean(), nullable=False),
        sa.Column("knowledge_base_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("verifier_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("report_markdown", sa.Text(), nullable=True),
        sa.Column("iteration_count", sa.Integer(), nullable=False),
        sa.Column("max_iterations", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_tasks_status"), "research_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_research_tasks_user_id"), "research_tasks", ["user_id"], unique=False)
    op.create_table(
        "research_steps",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("finding", sa.Text(), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["research_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_steps_status"), "research_steps", ["status"], unique=False)
    op.create_index(op.f("ix_research_steps_task_id"), "research_steps", ["task_id"], unique=False)
    op.create_table(
        "research_evidence",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_id", sa.String(length=2048), nullable=False),
        sa.Column("chunk_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["step_id"], ["research_steps.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["research_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_evidence_source_type"), "research_evidence", ["source_type"], unique=False
    )
    op.create_index(
        op.f("ix_research_evidence_step_id"), "research_evidence", ["step_id"], unique=False
    )
    op.create_index(
        op.f("ix_research_evidence_task_id"), "research_evidence", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_research_evidence_task_id"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_step_id"), table_name="research_evidence")
    op.drop_index(op.f("ix_research_evidence_source_type"), table_name="research_evidence")
    op.drop_table("research_evidence")
    op.drop_index(op.f("ix_research_steps_task_id"), table_name="research_steps")
    op.drop_index(op.f("ix_research_steps_status"), table_name="research_steps")
    op.drop_table("research_steps")
    op.drop_index(op.f("ix_research_tasks_user_id"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_status"), table_name="research_tasks")
    op.drop_table("research_tasks")
    # ### end Alembic commands ###
